import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  API_APP_NAME: Joi.string().optional(),
  APP_NAME: Joi.string().optional(),
  API_PORT: Joi.number().optional(),
  PORT: Joi.number().default(8000),
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  API_PREFIX: Joi.string().default('api'),
  API_FRONTEND_URL: Joi.string().optional(),
  FRONTEND_URL: Joi.string().default('http://localhost:3000'),
  API_CORS_ALLOWED_ORIGINS: Joi.string().optional().allow(''),
  CORS_ALLOWED_ORIGINS: Joi.string().optional().allow(''),
  API_DOCS_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  API_TRUST_PROXY: Joi.boolean().truthy('true').falsy('false').optional(),
  TRUST_PROXY: Joi.boolean().truthy('true').falsy('false').default(false),
  API_RATE_LIMIT_WINDOW_MS: Joi.number().integer().min(1000).optional(),
  RATE_LIMIT_WINDOW_MS: Joi.number().integer().min(1000).default(60000),
  API_RATE_LIMIT_MAX: Joi.number().integer().min(1).optional(),
  RATE_LIMIT_MAX: Joi.number().integer().min(1).default(180),
  API_DATABASE_URL: Joi.string().optional(),
  DATABASE_URL: Joi.string().optional(),
  API_DIRECT_URL: Joi.string().optional(),
  DIRECT_URL: Joi.string().optional(),
  API_AUTH_PROVIDER: Joi.string().optional(),
  AUTH_PROVIDER: Joi.string().default('supabase'),
  API_AUTH_URL: Joi.string().uri().optional(),
  AUTH_URL: Joi.string().uri().optional(),
  API_AUTH_PUBLIC_KEY: Joi.string().optional(),
  AUTH_PUBLIC_KEY: Joi.string().optional(),
  API_AUTH_SERVICE_KEY: Joi.string().optional(),
  AUTH_SERVICE_KEY: Joi.string().optional(),
  API_AUTH_JWT_SECRET: Joi.string().optional().allow(''),
  AUTH_JWT_SECRET: Joi.string().optional().allow(''),
  API_AUTH_JWKS_URL: Joi.string().uri().optional().allow(''),
  AUTH_JWKS_URL: Joi.string().uri().optional().allow(''),
  API_AUTH_JWT_ISSUER: Joi.string().uri().optional().allow(''),
  AUTH_JWT_ISSUER: Joi.string().uri().optional().allow(''),
  API_AUTH_JWT_AUDIENCE: Joi.string().optional().allow(''),
  AUTH_JWT_AUDIENCE: Joi.string().optional().allow(''),
  API_AUTH_REQUIRED_ROLE: Joi.string().optional().allow(''),
  AUTH_REQUIRED_ROLE: Joi.string().optional().allow(''),
  API_AUTH_ROLE_CLAIM: Joi.string().optional().allow(''),
  AUTH_ROLE_CLAIM: Joi.string().optional().allow(''),
  API_SUPABASE_URL: Joi.string().uri().optional(),
  SUPABASE_URL: Joi.string().uri().optional(),

  // Accept classic or new Supabase key names
  API_SUPABASE_ANON_KEY: Joi.string().optional(),
  SUPABASE_ANON_KEY: Joi.string().optional(),
  API_SUPABASE_PUBLISHABLE_KEY: Joi.string().optional(),
  SUPABASE_PUBLISHABLE_KEY: Joi.string().optional(),
  API_SUPABASE_SERVICE_ROLE_KEY: Joi.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: Joi.string().optional(),
  API_SUPABASE_SECRET_KEY: Joi.string().optional(),
  SUPABASE_SECRET_KEY: Joi.string().optional(),
  API_SUPABASE_JWT_SECRET: Joi.string().optional().allow(''),
  SUPABASE_JWT_SECRET: Joi.string().optional().allow(''),
  API_SUPABASE_JWKS_URL: Joi.string().uri().optional().allow(''),
  SUPABASE_JWKS_URL: Joi.string().uri().optional().allow(''),

  API_STORAGE_PROVIDER: Joi.string().optional(),
  STORAGE_PROVIDER: Joi.string().default('s3'),
  API_S3_ENDPOINT: Joi.string().uri().optional(),
  S3_ENDPOINT: Joi.string().uri().optional(),
  API_S3_PUBLIC_URL: Joi.string().optional(),
  S3_PUBLIC_URL: Joi.string().optional(),
  API_S3_BUCKET: Joi.string().optional(),
  S3_BUCKET: Joi.string().default('sasha-store'),
  API_S3_REGION: Joi.string().optional(),
  S3_REGION: Joi.string().default('us-east-1'),
  API_S3_ACCESS_KEY: Joi.string().optional(),
  S3_ACCESS_KEY: Joi.string().optional(),
  API_S3_SECRET_KEY: Joi.string().optional(),
  S3_SECRET_KEY: Joi.string().optional(),
  API_S3_FORCE_PATH_STYLE: Joi.boolean().truthy('true').falsy('false').optional(),
  S3_FORCE_PATH_STYLE: Joi.boolean().truthy('true').falsy('false').default(true),
  API_REDIS_URL: Joi.string().optional().allow(''),
  REDIS_URL: Joi.string().optional().allow(''),
  API_UPSTASH_REDIS_URL: Joi.string().uri().optional().allow(''),
  UPSTASH_REDIS_URL: Joi.string().uri().optional().allow(''),
  API_UPSTASH_REDIS_TOKEN: Joi.string().optional().allow(''),
  UPSTASH_REDIS_TOKEN: Joi.string().optional().allow(''),
  API_SUPABASE_DB_CACHE_ENABLED: Joi.boolean()
    .truthy('true')
    .falsy('false')
    .optional(),
  SUPABASE_DB_CACHE_ENABLED: Joi.boolean()
    .truthy('true')
    .falsy('false')
    .optional(),
  NAMECHEAP_SMTP_HOST: Joi.string().optional().allow(''),
  NAMECHEAP_SMTP_PORT: Joi.number().optional(),
  NAMECHEAP_SMTP_USER: Joi.string().optional().allow(''),
  NAMECHEAP_SMTP_PASSWORD: Joi.string().optional().allow(''),
  EMAIL_FROM: Joi.string().optional().allow(''),
  API_NAMECHEAP_SMTP_HOST: Joi.string().optional().allow(''),
  API_NAMECHEAP_SMTP_PORT: Joi.number().optional(),
  API_NAMECHEAP_SMTP_USER: Joi.string().optional().allow(''),
  API_NAMECHEAP_SMTP_PASSWORD: Joi.string().optional().allow(''),
  API_EMAIL_FROM: Joi.string().optional().allow(''),
  API_BULLMQ_REDIS_URL: Joi.string().uri().optional().allow(''),
  BULLMQ_REDIS_URL: Joi.string().uri().optional().allow(''),
})
  .or('API_DATABASE_URL', 'DATABASE_URL')
  .or('API_AUTH_URL', 'API_SUPABASE_URL', 'AUTH_URL', 'SUPABASE_URL')
  .or(
    'API_AUTH_PUBLIC_KEY',
    'API_SUPABASE_ANON_KEY',
    'API_SUPABASE_PUBLISHABLE_KEY',
    'AUTH_PUBLIC_KEY',
    'SUPABASE_ANON_KEY',
    'SUPABASE_PUBLISHABLE_KEY',
  )
  .or(
    'API_AUTH_SERVICE_KEY',
    'API_SUPABASE_SERVICE_ROLE_KEY',
    'API_SUPABASE_SECRET_KEY',
    'AUTH_SERVICE_KEY',
    'SUPABASE_SERVICE_ROLE_KEY',
    'SUPABASE_SECRET_KEY',
  )
  .or(
    'API_AUTH_JWT_SECRET',
    'API_AUTH_JWKS_URL',
    'API_SUPABASE_JWT_SECRET',
    'API_SUPABASE_JWKS_URL',
    'AUTH_JWT_SECRET',
    'AUTH_JWKS_URL',
    'SUPABASE_JWT_SECRET',
    'SUPABASE_JWKS_URL',
  );
